version: '3.8'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: panaderia
    ports:
      - "3310:3306"
    volumes:
      -C:\Users\monca\Desktop\Universidad\2025-1\arquitectura de software\ejercicio en clase docker compose\volumen_panaderia


  volumes:
  db-data:

